#! /bin/sh
#
# check_ruby last edited on Wed Apr 29 23:59:46 2026 
#
# Test against known data
#
echo 1. Test predefined test against known correct results
#
rm -f tstResults_ruby
#
# redirect both stdout and stderr output to tstResults file
#
./chk_decimal ruby ../bfbs.rb --quiet > tstResults_ruby 2>&1
diff -s tstResults_ruby correctResults_ruby
#
