#! /bin/sh
#
# check last edited on Mon Mar  2 19:41:08 2026 
#
# Test known data
#
echo 1. Test predefined test against known correct results
#
rm -f tstResults_rust
#
# redirect both stdout and stderr output to tstResults file
./chk_rust --quiet > tstResults_rust 2>&1
diff -s tstResults_rust correctResults_rust
#
