#! /bin/sh
#
# check_perl last edited on Sat Feb 28 17:04:17 2026 
#
# Test against known data
#
echo 1. Test predefined test against known correct results
#
rm -f tstResults_perl
#
# redirect both stdout and stderr output to tstResults file
#
./chk_decimal perl ../bfbs.pl --quiet > tstResults_perl 2>&1
diff -s tstResults_perl correctResults_perl
#
