#! /bin/sh
#
# check last edited on Mon Jun 10 23:16:31 2024 
#
# Test known data
#
echo 1. Test predefined test against known correct results
#
rm -f tstResults_go
#
# redirect both stdout and stderr output to tstResults file
./tst_go > tstResults_go 2>&1
diff -s tstResults_go correctResults_go
#
