#! /bin/sh
#
# check_ruby last edited on Sat Feb 28 15:27:29 2026 
#
# Test against known data
#
echo 1. Test predefined test against known correct results
#
rm -f tstResults_ruby
#
# redirect both stdout and stderr output to tstResults file
#
./tst_ruby > tstResults_ruby 2>&1
diff -s tstResults_ruby correctResults_ruby
#
