#! /bin/sh
#
# check last edited on Wed Apr 29 22:40:44 2026 
#
# Test known data
#
echo 1. Test predefined test against known correct results
#
rm -f tstResults_tcl
#
# redirect both stdout and stderr output to tstResults file
./chk_decimal tclsh ../bfbs.tcl --quiet > tstResults_tcl 2>&1
diff -s tstResults_tcl correctResults_tcl
#
