//
// B F B S . C P P
//
// Big Float Basic Statistics
//
// bfbs.cpp last updated on Sun Mar 29 17:17:46 2026 by O.H. as 0v8
//

//
// requires the following libraries; -
//  GMP (GNU Multiple Precision Arithmetic Library)
//  MPFR (Multiple Precision Floating-Point Reliable Library)
//
// On Ubuntu make sure the library code is installed with; -
//  sudo apt install libgmp-dev libmpfr-dev
// On MacOS one method to provide the library code is with homebrew; -
//  brew install gmp
//  brew install mpfr
//
// Compile on Ubuntu with; -
//  g++ -Wall -pedantic -Wextra -std=c++17 -o bfbs_cpp bfbs.cpp -lmpfr -lgmp
// Compile on MacOS (homebrew library code) with; -
//  g++ -Wall -pedantic -Wextra -std=c++17 -I /opt/homebrew/include/ -o bfbs_cpp bfbs.cpp -L /opt/homebrew/lib/ -lmpfr -lgmp
//
// Run with; -
//  ./bfbs_cpp data.csv
//
// Run with multiple files and options; -
//  ./bfbs_cpp data1withHdr.csv data2withHdr.csv --precision 512 --digits 80 --header
//
// Help / Usage is; -
// Usage:
// ../bfbs_cpp file1.csv [file2.csv ...] [--help] [--quiet] [--header] [--precision N] [--digits N]
//   where:
//     file1.csv [file2.csv ...]  - one or more CSV files to process
//     -h  or  --help             - show this help message and exit
//     -H  or  --header           - treat first CSV row as (text) column headers
//     -P  or  --precision N       - set calculation precision to N bits (default: 256)
//     -p  or  --print_digits N    - set output digits to N (default: 64)
//     -q  or  --quiet            - suppress version info and timing info
//

//
// Originally this code was generated by ChatGPT from the starting prompt; -
//
// Please write a c++ program that reads one or more comma separated value
// data files containing one or more columns of numbers and calculates the
// min, median, mean, max, range, sum, sample variance and sample standard
// deviation for each column using an arbitrary-precision floating point
// arithmetic package and prints out the results for each column in each file.
// Ensure that the program can handle leading spaces on numbers, blank rows
// in files and comment lines beginning with a hash. Allow the calculation
// precision and number of digits output when printing the results to be
// optionally controlled by the user from the command line. Also allow the
// user to optionally specify that the first row is a header of column names
// instead of numbers.
//

//
// 0v8 Calculate and output population variance and population standard deviation
//     in addition to sample variance and sample standard deviation.
// 0v7 Short form option parsing and help/usage message
// 0v6 More comprehensive argument parsing and more detailed help/usage message
// output to include all options and their descriptions
// 0v5 Minor change to help output and elapsed time message
// 0v4 Fixed compile and output execution time to uSec resolution
// 0v3 Added execution time output
// 0v2 Added --quiet option to suppress version info and increase output digits to 64
//

#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <algorithm>
#include <iomanip>
#include <mpfr.h>
#include <time.h>   // clock_gettime()

using namespace std;

#define PROGRAM_NAME __FILE__
#define PROGRAM_VERSION "0v8"

// RAII Wrapper for mpfr_t
class MpfrFloat {
public:
    mpfr_t value;

    MpfrFloat(int precision = 256) {
        mpfr_init2(value, precision);
    }

    MpfrFloat(const MpfrFloat& other) {
        mpfr_init2(value, mpfr_get_prec(other.value));
        mpfr_set(value, other.value, MPFR_RNDN);
    }

    MpfrFloat& operator=(const MpfrFloat& other) {
        if (this != &other) {
            mpfr_set(value, other.value, MPFR_RNDN);
        }
        return *this;
    }

    ~MpfrFloat() {
        mpfr_clear(value);
    }

    bool operator<(const MpfrFloat& other) const {
        return mpfr_less_p(value, other.value);
    }

    bool operator>(const MpfrFloat& other) const {
        return mpfr_greater_p(value, other.value);
    }
};

struct Options {
    int precision = 256;
    int digits = 64;
    bool hasHeader = false;
    bool quiet = false;
    bool help = false;
    vector<string> files;
};

Options parseArgs(int argc, char* argv[]) {
    Options opts;
    for (int i = 1; i < argc; ++i) {
        string arg = argv[i];
        if (((arg == "--precision") || (arg == "-P")) && i + 1 < argc) {
            opts.precision = stoi(argv[++i]);
        } else if (((arg == "--print_digits") || (arg == "-p")) && i + 1 < argc) {
            opts.digits = stoi(argv[++i]);
        } else if ((arg == "--header") || (arg == "-H")) {
            opts.hasHeader = true;
        } else if ((arg == "--quiet") || (arg == "-q")) {
            opts.quiet = true;
        } else if ((arg == "--help") || (arg == "-h")) {
            opts.help = true;
        } else if (arg.rfind("-", 0) == 0) {    /* known options have already been tested */
            cerr << "\nWarning: Skipping unknown option: \"" << arg;
            cerr << "\"\nUse -h or --help to see usage information.\n\n";
        } else {
            opts.files.push_back(arg);
        }
    }
    if (opts.files.empty() || opts.help) {
        cerr << "Usage:" << endl;
        cerr << argv[0];    // program name
        cerr << " file1.csv [file2.csv ...] [--help] [--header] [--print_digits N] [--precision N] [--quiet]\n";
        cerr << "  where:\n";
        cerr << "    file1.csv [file2.csv ...]  - one or more CSV files to process\n";
        cerr << "    -h  or  --help             - show this help message and exit\n";
        cerr << "    -H  or  --header           - treat first CSV row as (text) column headers\n";
        cerr << "    -p  or --print_digits N    - set output digits to N (default: 64)\n";
        cerr << "    -P  or --precision N       - set calculation precision to N bits (default: 256)\n";
        cerr << "    -q  or  --quiet            - suppress version info and timing info\n";
        exit(1);
    }
    return opts;
}

void printBanner(const Options& opts) {
    if( ! opts.quiet ) {
        cout << PROGRAM_NAME << " version " << PROGRAM_VERSION << endl;
        cout << "Compiler version: " << __VERSION__ << endl;

        cout << "MPFR version: " << mpfr_get_version() << endl;
        cout << "GMP version:  " << gmp_version << endl;
    }
    cout << "Using " << opts.precision << " bits Calculation precision ";
    cout << "and " << opts.digits << " digits Output precision ";
    cout << "with Rounding mode: MPFR_RNDN (round to nearest)" << endl;
    cout << endl;
}

int readCSV(const string& filename, vector<vector<MpfrFloat>>& columns, vector<string>& headers, bool hasHeader, int precision) {
    ifstream file(filename);
    if (!file) {
        cerr << "Error: Cannot open file: " << filename << endl;
        return(1);  // failure due to file open error
    }

    string line;
    bool firstLine = true;

    while (getline(file, line)) {
        line.erase(0, line.find_first_not_of(" \t\r\n"));
        line.erase(line.find_last_not_of(" \t\r\n") + 1);

        if (line.empty() || line[0] == '#') continue;

        stringstream ss(line);
        string cell;
        vector<string> cells;
        while (getline(ss, cell, ',')) {
            size_t start = cell.find_first_not_of(" \t");
            cells.push_back(start != string::npos ? cell.substr(start) : "");
        }

        if (firstLine && hasHeader) {
            headers = cells;
            firstLine = false;
            continue;
        }

        if (columns.size() < cells.size()) {
            columns.resize(cells.size());
        }

        for (size_t i = 0; i < cells.size(); ++i) {
            MpfrFloat val(precision);
            if (mpfr_set_str(val.value, cells[i].c_str(), 10, MPFR_RNDN) != 0) {    // base 10 i.e. decimal is assumed
                cerr << "Invalid number: " << cells[i] << " in file " << filename << endl;
                exit(1);
            }
            columns[i].push_back(val);
        }

        firstLine = false;
    }
    return(0);  // success
}

vector<MpfrFloat> sortColumn(const vector<MpfrFloat>& col) {
    vector<MpfrFloat> sorted = col;
    sort(sorted.begin(), sorted.end());
    return sorted;
}

void computeStats(const vector<MpfrFloat>& col, int precision, int base, int digits, const string& name) {
    size_t n = col.size();
    if (n == 0) return;

    mpfr_t sum, mean, minVal, maxVal, range, var, stddev, pvar, pstddev, temp, diff, median;
    mpfr_inits2(precision, sum, mean, minVal, maxVal, range, var, stddev, pvar, pstddev, temp, diff, median, (mpfr_ptr) nullptr);

    mpfr_set(sum, col[0].value, MPFR_RNDN);
    mpfr_set(minVal, col[0].value, MPFR_RNDN);
    mpfr_set(maxVal, col[0].value, MPFR_RNDN);

    for (size_t i = 1; i < n; ++i) {
        mpfr_add(sum, sum, col[i].value, MPFR_RNDN);
        if (mpfr_less_p(col[i].value, minVal)) mpfr_set(minVal, col[i].value, MPFR_RNDN);
        if (mpfr_greater_p(col[i].value, maxVal)) mpfr_set(maxVal, col[i].value, MPFR_RNDN);
    }

    mpfr_set_ui(temp, n, MPFR_RNDN);
    mpfr_div(mean, sum, temp, MPFR_RNDN);       /* mean = sum / n */
    mpfr_sub(range, maxVal, minVal, MPFR_RNDN); /* range = max - min */

    // Sample variance
    mpfr_set_zero(var, 1);
    for (const auto& val : col) {
        mpfr_sub(diff, val.value, mean, MPFR_RNDN);     /* diff = val - mean */
        mpfr_mul(diff, diff, diff, MPFR_RNDN);          /* diff squared */
        mpfr_add(var, var, diff, MPFR_RNDN);            /* totalize the diff squared values */
    }
    if (n > 0) {
        mpfr_div(pvar, var, temp, MPFR_RNDN);   /* population variance = total diff squared / n */
    }
    if (n > 1) {
        mpfr_set_ui(temp, n - 1, MPFR_RNDN);
        mpfr_div(var, var, temp, MPFR_RNDN);    /* sample variance = total diff squared / (n - 1) */
    }

    mpfr_sqrt(stddev, var, MPFR_RNDN);
    mpfr_sqrt(pstddev, pvar, MPFR_RNDN);

    // Median
    vector<MpfrFloat> sorted = sortColumn(col);
    if (n % 2 == 1) {
        mpfr_set(median, sorted[n / 2].value, MPFR_RNDN);
    } else {
        mpfr_add(median, sorted[n / 2 - 1].value, sorted[n / 2].value, MPFR_RNDN);
        mpfr_div_ui(median, median, 2, MPFR_RNDN);
    }

    // Output
    cout << "Column: " << name << endl;
    cout << "  Count            : " << n << endl;
    cout << fixed << setprecision(digits);
    cout << "  Minimum       : "; mpfr_out_str(stdout, base, digits, minVal, MPFR_RNDN); cout << endl;
    cout << "  Mean          : "; mpfr_out_str(stdout, base, digits, mean, MPFR_RNDN); cout << endl;
    cout << "  Median        : "; mpfr_out_str(stdout, base, digits, median, MPFR_RNDN); cout << endl;
    cout << "  Maximum       : "; mpfr_out_str(stdout, base, digits, maxVal, MPFR_RNDN); cout << endl;
    cout << "  Range         : "; mpfr_out_str(stdout, base, digits, range, MPFR_RNDN); cout << endl;
    cout << "  Sum           : "; mpfr_out_str(stdout, base, digits, sum, MPFR_RNDN); cout << endl;
    cout << "  Variance (s²) : "; mpfr_out_str(stdout, base, digits, var, MPFR_RNDN); cout << endl;
    cout << "  Std. Dev. (s) : "; mpfr_out_str(stdout, base, digits, stddev, MPFR_RNDN); cout << endl;
    cout << "  Variance (σ²) : "; mpfr_out_str(stdout, base, digits, pvar, MPFR_RNDN); cout << endl;
    cout << "  Std. Dev. (σ) : "; mpfr_out_str(stdout, base, digits, pstddev, MPFR_RNDN); cout << endl;
    cout << endl;

    mpfr_clears(sum, mean, minVal, maxVal, range, var, stddev, pvar, pstddev, temp, diff, median, (mpfr_ptr) nullptr);
}

int main(int argc, char* argv[]) {
    int time_ok;
    int result_flag = 0;
    double  elapsed_wall_clock_time;
    struct timespec  start_time;
    struct timespec  finish_time;

    time_ok = (clock_gettime(CLOCK_MONOTONIC, &start_time) == 0);
    Options opts = parseArgs(argc, argv);
    printBanner(opts);

    for (const auto& file : opts.files) {
        cout << "Processing file: " << file << endl;
        vector<vector<MpfrFloat>> columns;
        vector<string> headers;

        if ( readCSV(file, columns, headers, opts.hasHeader, opts.precision ) != 0 ) {
            result_flag |= 1;   // remember there was a failure
            continue;   // failure so proceed to next file if there is one
        }

        for (size_t i = 0; i < columns.size(); ++i) {
            string name = (opts.hasHeader && i < headers.size()) ? headers[i] : "Column " + to_string(i + 1);
            computeStats(columns[i], opts.precision, 10, opts.digits, name);    // base 10 - i.e. decimal output
        }
    }

    if( ! opts.quiet && time_ok && ( clock_gettime(CLOCK_MONOTONIC, &finish_time ) == 0 )) {
        elapsed_wall_clock_time = (double)( finish_time.tv_sec - start_time.tv_sec ) +
            ( double )( finish_time.tv_nsec - start_time.tv_nsec ) * (double)(1.0e-9);
        printf( "%s (c++ executable) time taken: %9.6lf [sec]\n", argv[0], elapsed_wall_clock_time );
    }
    return result_flag;
}
