#! /bin/bash
#
# C O N F I G U R E _ C P P
#
# configure last edited on Sun Nov 30 13:36:25 2025 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER="g++"
OPTIONS="-Wall -pedantic -Wextra -std=c++17"
LNK_OPTIONS="-lmpfr -lgmp"
RELEASE_LNK_OPTIONS="-static -lmpfr -lgmp"
TRGT=${NAME1}_cpp
SRC1=${NAME1}.cpp
#
# Determine generic OS name, e.g. 'darwin'
OS_FAMILY="${OSTYPE%[0-9][0-9]}"
#
# Adjust for homebrew installed arbitrary precision math library files on MacOS
if [[ "$OS_FAMILY" == "darwin" ]]; then
    OPTIONS="-Wall -pedantic -Wextra -std=c++17 -I /opt/homebrew/include/"
    LNK_OPTIONS="-L /opt/homebrew/lib/ -lmpfr -lgmp"
    # -static has problems on MacOS
    RELEASE_LNK_OPTIONS=$LNK_OPTIONS
fi
#
echo "$TRGT: $SRC1" > $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -o "'$@ $^'" $LNK_OPTIONS" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check_cpp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk_cpp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f $TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -DDEBUG -o $TRGT $SRC1 $LNK_OPTIONS" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "static: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -DDEBUG -o $TRGT $SRC1 -static $LNK_OPTIONS" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
# Release target with optimization and stripped binary
echo "release: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -O2 -o $TRGT $SRC1 $RELEASE_LNK_OPTIONS" >> $OP_FILE_NAME
echo -e "\tstrip $TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
