#! /bin/bash
#
# C O N F I G U R E _ R U S T
#
# configure last edited on Sat Sep 27 22:13:13 2025 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER=cargo
OPTIONS="build"
LNK_OPTIONS=""
TRGT=${NAME1}_rust
SRC1=src/main.rs
#
#
echo "$TRGT: $SRC1" > $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS $LNK_OPTIONS" >> $OP_FILE_NAME
echo -e "\trsync -vut target/debug/${NAME1} ./$TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check_rust" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk_rust" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f $TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS $LNK_OPTIONS" >> $OP_FILE_NAME
echo -e "\trsync -vut bin/debug/${NAME1} ./$TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
