#! /bin/bash
#
# C O N F I G U R E
#
# configure last edited on Sun Aug  3 22:13:13 2025 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER=julia
OPTIONS=""
LNK_OPTIONS=""
TRGT=$NAME1.jl
SRC1=$NAME1.jl
#
#
echo "$TRGT: configure Makefile" > $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f *.tmp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --debug --verbose" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "version:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "help:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --help" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
