#! /bin/bash
#
# C O N F I G U R E _ P Y T H O N
#
# configure last edited on Sun Aug  3 22:13:13 2025 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER="python3"
OPTIONS=""
LNK_OPTIONS=""
TRGT=$NAME1
SRC1=$NAME1.py
#
#
echo "$TRGT: configure_python Makefile" > $OP_FILE_NAME
echo -e "\tpython3 --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check_python" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk_python" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f *.tmp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --debug --verbose" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "version:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "help:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --help" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
