#! /bin/bash
#
# C O N F I G U R E _ T C L
#
# configure_tcl last edited on Sat Mar  7 10:21:19 2026 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER="tclsh"
OPTIONS=""
LNK_OPTIONS=""
TRGT=$NAME1
SRC1=$NAME1.tcl
#
#
echo "$TRGT: configure_tcl Makefile" > $OP_FILE_NAME
echo -e "\t${COMPILER} ${SRC1} --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check_tcl" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk_decimal ${COMPILER} ../${SRC1}" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f *.tmp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug:" >> $OP_FILE_NAME
echo -e "\t${COMPILER} ${SRC1} --debug --verbose" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "version:" >> $OP_FILE_NAME
echo -e "\t${COMPILER} ${SRC1} --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "help:" >> $OP_FILE_NAME
echo -e "\t${COMPILER} ${SRC1} --help" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
