#! /bin/bash
#
# C O N F I G U R E _ R U B Y
#
# configure_ruby last edited on Sat Feb 28 16:16:15 2026 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER="ruby"
OPTIONS=""
LNK_OPTIONS=""
TRGT=$NAME1
SRC1=$NAME1.rb
#
#
echo "$TRGT: configure_ruby Makefile" > $OP_FILE_NAME
echo -e "\truby --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check_ruby" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk_ruby" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f *.tmp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --debug --verbose" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "version:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --version" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "help:" >> $OP_FILE_NAME
echo -e "\t$COMPILER $SRC1 --help" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
