#! /bin/bash
#
# C O N F I G U R E _ C P P
#
# configure last edited on Sat Sep 29 21:13:13 2025 
#
NAME1=bfbs
#
OP_FILE_NAME=Makefile
COMPILER="g++"
OPTIONS="-Wall -pedantic -Wextra -std=c++17 -I /opt/homebrew/include/"
LNK_OPTIONS="-L /opt/homebrew/lib/ -lmpfr -lgmp"
TRGT=${NAME1}_cpp
SRC1=${NAME1}.cpp
#
#
echo "$TRGT: $SRC1" > $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -o "'$@ $^'" $LNK_OPTIONS" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "check: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./check_cpp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "chk: $TRGT" >> $OP_FILE_NAME
echo -e "\tcd test; ./chk_cpp" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "clean:" >> $OP_FILE_NAME
echo -e "\trm -f $TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "debug: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -DDEBUG -o $TRGT $SRC1 $LNK_OPTIONS" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "static: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -DDEBUG -o $TRGT $SRC1 -static $LNK_OPTIONS" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
echo "release: clean" >> $OP_FILE_NAME
echo -e "\t$COMPILER $OPTIONS -O2 -o $TRGT $SRC1 -static $LNK_OPTIONS" >> $OP_FILE_NAME
echo -e "\tstrip $TRGT" >> $OP_FILE_NAME
echo "" >> $OP_FILE_NAME
#
